"""Packs the MediaPipe<->GNM correspondence into a JS module for the demo.

The correspondence maps MediaPipe FaceLandmarker points onto GNM vertices and
records where the landmarker places each point on a neutral GNM face. It is
small enough (~8 KB) that inlining it as base64 beats a second network fetch,
and it keeps the demo working from a file:// URL.

Source is the npz shipped by https://github.com/edualvarado/gnm-webcam-puppet,
which derives it against the same GNM 3.0 head this demo loads.

Usage:
  python -m tools.export_face_correspondence \
      --npz references/gnm-webcam-puppet/webcam_puppet/assets/correspondence.npz \
      --out ../../samples/avatar_lab/gnm/FaceCorrespondence.js
"""

import argparse
import base64
import os

import numpy as np

# Section order is chosen so every typed-array view lands on its natural
# alignment when the decoded bytes are read back as one ArrayBuffer.
_TEMPLATE = '''/**
 * FaceCorrespondence.js — MediaPipe FaceLandmarker <-> GNM vertex mapping.
 *
 * GENERATED by tools/export_face_correspondence.py. Do not edit by hand.
 *
 * `landmarks[i]` is a MediaPipe landmark index and `vertices[i]` the GNM vertex
 * it lands on. `reference[i]` is where the landmarker places that point on a
 * neutral GNM face — fitting displacement from this cloud rather than from the
 * template vertices is what cancels the landmarker's own idea of face shape,
 * which otherwise reads as a very deep face and bakes itself into identity.
 * `rigid[i]` marks the {rigidCount} skull-fixed points, the ones whose vertices barely
 * move with expression; identity is solved on those alone so an expression at
 * capture time cannot be absorbed into it.
 *
 * Source: https://github.com/edualvarado/gnm-webcam-puppet (Apache-2.0),
 * derived against the same GNM 3.0 head this demo loads.
 */

const COUNT = {count};
const PACKED = '{payload}';

function decode() {{
  const binary = atob(PACKED);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; ++i) bytes[i] = binary.charCodeAt(i);
  const buffer = bytes.buffer;
  return {{
    count: COUNT,
    reference: new Float32Array(buffer, {reference_offset}, COUNT * 3),
    landmarks: new Uint16Array(buffer, {landmarks_offset}, COUNT),
    vertices: new Uint16Array(buffer, {vertices_offset}, COUNT),
    rigid: new Uint8Array(buffer, {rigid_offset}, COUNT),
  }};
}}

/**
 * The correspondence, decoded once on first use.
 *
 * @type {{{{count: number, reference: Float32Array, landmarks: Uint16Array,
 *   vertices: Uint16Array, rigid: Uint8Array}}}}
 */
export const FACE_CORRESPONDENCE = decode();

/** Highest MediaPipe landmark index referenced; a frame must be this long. */
export const REQUIRED_LANDMARKS = {required};
'''


def main() -> None:
  parser = argparse.ArgumentParser(description=__doc__)
  parser.add_argument('--npz', required=True, help='correspondence.npz path.')
  parser.add_argument('--out', required=True, help='Output .js path.')
  args = parser.parse_args()

  data = np.load(args.npz)
  landmarks = data['landmark_indices'].astype(np.uint16)
  vertices = data['vertex_indices'].astype(np.uint16)
  rigid = data['rigid'].astype(np.uint8)
  reference = np.ascontiguousarray(
      data['reference_landmarks'], dtype=np.float32
  )

  count = int(landmarks.shape[0])
  if not (vertices.shape[0] == rigid.shape[0] == count):
    raise ValueError('Correspondence arrays disagree in length.')
  if reference.shape != (count, 3):
    raise ValueError(f'Expected reference of shape ({count}, 3).')

  blob = b''.join(
      (reference.tobytes(), landmarks.tobytes(), vertices.tobytes(),
       rigid.tobytes())
  )
  reference_bytes = reference.nbytes
  landmarks_offset = reference_bytes
  vertices_offset = landmarks_offset + landmarks.nbytes
  rigid_offset = vertices_offset + vertices.nbytes

  source = _TEMPLATE.format(
      count=count,
      rigidCount=int(rigid.sum()),
      payload=base64.b64encode(blob).decode('ascii'),
      reference_offset=0,
      landmarks_offset=landmarks_offset,
      vertices_offset=vertices_offset,
      rigid_offset=rigid_offset,
      required=int(landmarks.max()) + 1,
  )
  os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
  with open(args.out, 'w', encoding='utf-8', newline='\n') as f:
    f.write(source)

  print(
      f'Wrote {args.out}: {count} correspondences '
      f'({int(rigid.sum())} rigid), {len(blob)} packed bytes.'
  )


if __name__ == '__main__':
  main()
